---
title: 'Comparison Report (`r params$condition` vs. `r params$control`)'
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    df_print: paged

params:
  pval_cutoff: 0.05
  pval_cutoff_miRNA: 0.1
  lfc_cutoff: 0
  low_counts_cutoff: 10
  col_data: ''
  counts_paper: ''
  counts_project: ''
  counts_miRNA: ''
  condition: ''
  control: ''
  mm_ensembl_entrez: ''
  mm_ensembl_symbol: ''
  mm_h: ''
  mm_c5_bp: ''
  mm_c5_cc: ''
  mm_c5_mf: ''
---

<style>
pre code, pre, code {
  white-space: pre !important;
  overflow-x: auto !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
</style>

```{r setup, include = F}
options(width = 10000)

library(tidyverse)
library(scales)
library(DESeq2)
library(pheatmap)
library(RColorBrewer)
library(fgsea)
library(VennDiagram)
library(multiMiR)

select <- dplyr::select

pval_cutoff <- params$pval_cutoff
pval_cutoff_miRNA <- params$pval_cutoff_miRNA
lfc_cutoff <- params$lfc_cutoff
low_counts_cutoff <- params$low_counts_cutoff

mm_ensembl_entrez <- params$mm_ensembl_entrez
mm_ensembl_symbol <- params$mm_ensembl_symbol

mm_h <- params$mm_h
mm_c5_bp <- params$mm_c5_bp
mm_c5_cc <- params$mm_c5_cc
mm_c5_mf <- params$mm_c5_mf

condition <- params$condition
control <- params$control
col_data <- params$col_data
counts_paper <- params$counts_paper
counts_project <- params$counts_project
counts_miRNA <- params$counts_miRNA

colors_default <- c('#00d5dc', '#ff877e')


get_DESeqDataSet_obj <- function(cnts, design_formula, counts_threshold = low_counts_cutoff) {
  
  col_data <- col_data %>%
    filter(Run %in% names(cnts))
  
  col_data <- col_data[match(names(cnts), col_data$Run),] %>%
    column_to_rownames(var = 'Run')
  
  print(all(rownames(col_data) %in% colnames(cnts)))
  print(all(rownames(col_data) == colnames(cnts)))
  
  dds <- DESeqDataSetFromMatrix(countData = as.matrix(round(cnts)),
                                colData = col_data,
                                design = design_formula)
  
  print(summary(dds))
  
  # Filter rows with low counts
  keep <- rowSums(counts(dds)) >= counts_threshold
  dds <- dds[keep, ]
  
  print(summary(dds))
  
  dds
}

get_transformed_data <- function(dds, transformation_type = 'rlog', blind = T) {
  if (transformation_type == 'vst') {
    dds_transformed <- vst(dds, blind = blind)
  } else {
    dds_transformed <- rlog(dds, blind = blind)
  }
  
  list(
    matrix = assay(dds_transformed),
    pca = prcomp(t(assay(dds_transformed)))
  )
}

get_fgsea_res <- function(rank_vec, genesets_list) {
  fgsea(
    pathways = genesets_list,
    stats = rank_vec,
    nperm = 1000,
    minSize = 15,
    maxSize = 500
  ) %>%
    as_tibble() %>%
    arrange(desc(NES))
}

plot_enrichment_table <- function(gsea_res, rank_vec, genesets_list, n_top = 10) {
  top_pathways_up <- gsea_res %>% filter(ES > 0) %>% arrange(padj) %>% head(n_top)
  top_pathways_down <- gsea_res %>% filter(ES < 0) %>% arrange(padj) %>% head(n_top)
  top_pathways <- bind_rows(top_pathways_up, top_pathways_down) %>% arrange(-NES)

  plotGseaTable(
    genesets_list[top_pathways$pathway], 
    rank_vec, 
    gsea_res, 
    gseaParam = 0.5
  )
}
```

```{r, echo = F}
writeLines(str_c('pval_cutoff: ', pval_cutoff))
writeLines(str_c('pval_cutoff_miRNA: ', pval_cutoff_miRNA))
writeLines(str_c('lfc_cutoff: ', lfc_cutoff))
writeLines(str_c('low_counts_cutoff: ', low_counts_cutoff))
```


# Paper DE results

```{r, message = F, warning = F}
# Create DESeqDataSet object
dds_paper <- get_DESeqDataSet_obj(counts_paper, ~ treatment)

# DE analysis using Wald test
dds_paper <- DESeq(dds_paper)
colData(dds_paper)

# Wald test results
res_paper <- results(
  dds_paper,
  contrast = c('treatment', condition, control),
  alpha = pval_cutoff
)
summary(res_paper)
```


# Project DE results

```{r, message = F, warning = F}
# Create DESeqDataSet object
dds_project <- get_DESeqDataSet_obj(counts_project, ~ treatment)

# DE analysis using Wald test
dds_project <- DESeq(dds_project)
colData(dds_project)

# Wald test results
res_project <- results(
  dds_project,
  contrast = c('treatment', condition, control),
  alpha = pval_cutoff
)
summary(res_project)
```


# miRNA DE results

```{r, message = F, warning = F}
# Create DESeqDataSet object
dds_miRNA <- get_DESeqDataSet_obj(counts_miRNA, ~ treatment, counts_threshold = 5)

# DE analysis using Wald test
dds_miRNA <- DESeq(dds_miRNA)
colData(dds_miRNA)

# Wald test results
res_miRNA <- results(
  dds_miRNA,
  contrast = c('treatment', condition, control),
  alpha = pval_cutoff_miRNA
)
summary(res_miRNA)
```

```{r, echo = F, message = F, results = 'hide'}
# Paper data
res_paper_df <- res_paper %>%
  data.frame() %>% 
  rownames_to_column(var = 'ensembl_gene_id') %>% 
  as_tibble()

res_paper_sig_df <- res_paper_df %>%
  filter(padj < pval_cutoff, abs(log2FoldChange) >= lfc_cutoff)

res_paper_up_df <- res_paper_sig_df %>%
  filter(log2FoldChange > 0)

res_paper_down_df <- res_paper_sig_df %>%
  filter(log2FoldChange < 0)


# Project data
res_project_df <- res_project %>%
  data.frame() %>% 
  rownames_to_column(var = 'ensembl_gene_id') %>% 
  as_tibble()

res_project_sig_df <- res_project_df %>%
  filter(padj < pval_cutoff, abs(log2FoldChange) >= lfc_cutoff)

res_project_up_df <- res_project_sig_df %>%
  filter(log2FoldChange > 0)

res_project_down_df <- res_project_sig_df %>%
  filter(log2FoldChange < 0)


# miRNA data
res_miRNA_df <- res_miRNA %>%
  data.frame() %>% 
  rownames_to_column(var = 'miRNA_name') %>% 
  as_tibble()

res_miRNA_sig_df <- res_miRNA_df %>%
  filter(padj < pval_cutoff_miRNA)

res_miRNA_up_df <- res_miRNA_sig_df %>%
  filter(log2FoldChange > 0)

res_miRNA_down_df <- res_miRNA_sig_df %>%
  filter(log2FoldChange < 0)


# miRNA target genes
multimir_up_res <- get_multimir(
  org = 'mmu',
  mirna = res_miRNA_up_df$miRNA_name,
  table = 'validated',
  summary = T
)

multimir_down_res <- get_multimir(
  org = 'mmu',
  mirna = res_miRNA_down_df$miRNA_name,
  table = 'validated',
  summary = T
)
```

```{r}
# Upregulated miRNA
res_miRNA_up_df$miRNA_name

# Upregulated miRNA that appeared in multimiR DB
unique(multimir_up_res@data$mature_mirna_id)

# Upregulated miRNA's target genes
unique(multimir_up_res@data$target_ensembl) %>% length()


# Downregulated miRNA
res_miRNA_down_df$miRNA_name

# Downregulated miRNA that appeared in multimiR DB
unique(multimir_down_res@data$mature_mirna_id)

# Downregulated miRNA's target genes
unique(multimir_down_res@data$target_ensembl) %>% length()
```


# DE genes comparison

```{r}
# All genes
grid::grid.draw(
  venn.diagram(
    list(paper = res_paper_df$ensembl_gene_id, project = res_project_df$ensembl_gene_id),
    fill = c('#F2F0F7', '#DADAEB'),
    filename = NULL
  )
)
```

## DE genes

```{r}
# DE genes
grid::grid.draw(
  venn.diagram(
    list(
      paper = res_paper_sig_df$ensembl_gene_id,
      project = res_project_sig_df$ensembl_gene_id
    ),
    fill = c('#EFF3FF', '#C6DBEF'),
    filename = NULL
  )
)

base::intersect(res_paper_sig_df$ensembl_gene_id, res_project_sig_df$ensembl_gene_id)
```

```{r}
grid::grid.draw(
  venn.diagram(
    list(
      paper = res_paper_sig_df$ensembl_gene_id,
      project = res_project_sig_df$ensembl_gene_id,
      miRNA_targets = c(unique(multimir_up_res@data$target_ensembl), unique(multimir_down_res@data$target_ensembl))
    ),
    fill = c('#EFF3FF', '#C6DBEF', '#FFE4E1'),
    filename = NULL
  )
)
```

## Upregulated genes

```{r}
# Upregulated genes
grid::grid.draw(
  venn.diagram(
    list(
      paper = res_paper_up_df$ensembl_gene_id,
      project = res_project_up_df$ensembl_gene_id
    ),
    fill = c('#EDF8E9', '#C7E9C0'),
    filename = NULL
  )
)

base::intersect(res_paper_up_df$ensembl_gene_id, res_project_up_df$ensembl_gene_id)
```

```{r}
grid::grid.draw(
  venn.diagram(
    list(
      paper = res_paper_up_df$ensembl_gene_id,
      project = res_project_up_df$ensembl_gene_id,
      miRNA_down_targets = unique(multimir_down_res@data$target_ensembl)
    ),
    fill = c('#EDF8E9', '#C7E9C0', '#FFE4E1'),
    filename = NULL
  )
)
```


## Downregulated genes

```{r}
# Downregulated genes
grid::grid.draw(
  venn.diagram(
    list(
      paper = res_paper_down_df$ensembl_gene_id,
      project = res_project_down_df$ensembl_gene_id
    ),
    fill = c('#FEE5D9', '#FCBBA1'),
    filename = NULL
  )
)

base::intersect(res_paper_down_df$ensembl_gene_id, res_project_down_df$ensembl_gene_id)
```

```{r}
grid::grid.draw(
  venn.diagram(
    list(
      paper = res_paper_down_df$ensembl_gene_id,
      project = res_project_down_df$ensembl_gene_id,
      miRNA_up_targets = unique(multimir_up_res@data$target_ensembl)
    ),
    fill = c('#FEE5D9', '#FCBBA1', '#FFE4E1'),
    filename = NULL
  )
)
```
